### ISSUE TITLE
Validity check failing

### ISSUE THREAD

**Issue by HaHeho** [andresperezlopez/pysofaconventions#1]
Using the latest version of your API from PyPI (I assume that is identical to the current version in the repo?). Loading supposedly valid SOFA files like MIT KEMAR (http://sofacoustics.org/data/database/mit/mit_kemar_normal_pinna.sofa) or THK KU100 (http://sofacoustics.org/data/database/thk/HRIR_L2702.sofa).

Checking the validity fails by `SOFAWarning: Missing Variable Attribute: ListenerUp.Units` and also some other attributes (havn't checked in detail which else yet).

The convention (https://www.sofaconventions.org/mediawiki/index.php/SimpleFreeFieldHRIR) says that these attributes are not mandatory, i.e. optional I suppose. I think we should modify the validity check accordingly?

**Comment by HaHeho** [comment]
It seems to be only `ListenerUp.Units` and `ListenerUp.Coordinates`. And exactly those are absent from the convention in case of ListenerUp (which is reasonable I would say).

**Comment by andresperezEUT** [comment]
Thanks for the point. It was indeed my fault. The bug is fixed in the last commit 17f8826e4d7b5814d2363b8c91b1a858bec54cd1 (v0.1.4), and I've tested manually the proper behavior of the SOFA files you specify. The changes will be reflected in the pypi package ASAP.
